services:
  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=FarsightRpcProviders;Username=postgres;Password=password
      - ASPNETCORE_HTTP_PORTS=8080
      - BootstrapAdmin__UserName=admin
      - BootstrapAdmin__Password=change-me
      - BootstrapViewerClient__Name=default-sdk
      - BootstrapViewerClient__ApiKey=change-me-viewer-key
    depends_on:
      - db
    restart: always
    networks:
      - internal
      - nginxmanager_proxy

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=FarsightRpcProviders
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - internal

volumes:
  postgres_data:

networks:
  internal:
  nginxmanager_proxy:
    external: true
