// <auto-generated />
using System;
using Farsight.Rpc.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Farsight.Rpc.Api.Persistence.Migrations
{
    [DbContext(typeof(RpcProvidersDbContext))]
    partial class RpcProvidersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Farsight.Rpc.Api.Persistence.Entities.ApiClientEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Environment")
                        .HasColumnType("integer");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApiKey")
                        .IsUnique();

                    b.HasIndex("ApplicationId");

                    b.ToTable("api_clients", (string)null);
                });

            modelBuilder.Entity("Farsight.Rpc.Api.Persistence.Entities.ApplicationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("applications", null, t =>
                        {
                            t.HasCheckConstraint("CK_applications_Name_NotEmpty", "btrim(\"Name\") <> ''");
                        });
                });

            modelBuilder.Entity("Farsight.Rpc.Api.Persistence.Entities.ArchiveEndpointEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChainId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("DexIndexStepSize")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("Environment")
                        .HasColumnType("integer");

                    b.Property<decimal>("IndexBlockOffset")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("IndexerStepSize")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset?>("ProbedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChainId");

                    b.HasIndex("ProviderId");

                    b.HasIndex("ApplicationId", "Environment", "ChainId");

                    b.ToTable("rpc_archive_endpoints", null, t =>
                        {
                            t.HasCheckConstraint("CK_rpc_archive_endpoints_Address_Scheme", "\"Address\" ~* '^(http|https|ws|wss)://'");
                        });
                });

            modelBuilder.Entity("Farsight.Rpc.Api.Persistence.Entities.ChainEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("chains", null, t =>
                        {
                            t.HasCheckConstraint("CK_chains_Name_NotEmpty", "btrim(\"Name\") <> ''");
                        });
                });

            modelBuilder.Entity("Farsight.Rpc.Api.Persistence.Entities.ProviderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("providers", null, t =>
                        {
                            t.HasCheckConstraint("CK_providers_Name_NotEmpty", "btrim(\"Name\") <> ''");
                        });
                });

            modelBuilder.Entity("Farsight.Rpc.Api.Persistence.Entities.ProviderRateLimitEntity", b =>
                {
                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid");

                    b.Property<int>("RateLimit")
                        .HasColumnType("integer");

                    b.HasKey("ProviderId");

                    b.ToTable("provider_rate_limits", null, t =>
                        {
                            t.HasCheckConstraint("CK_provider_rate_limits_RateLimit_Positive", "\"RateLimit\" > 0");
                        });
                });

            modelBuilder.Entity("Farsight.Rpc.Api.Persistence.Entities.RealTimeEndpointEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChainId")
                        .HasColumnType("uuid");

                    b.Property<int>("Environment")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ProbedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChainId");

                    b.HasIndex("ProviderId");

                    b.HasIndex("ApplicationId", "Environment", "ChainId");

                    b.ToTable("rpc_realtime_endpoints", null, t =>
                        {
                            t.HasCheckConstraint("CK_rpc_realtime_endpoints_Address_Scheme", "\"Address\" ~* '^(http|https|ws|wss)://'");
                        });
                });

            modelBuilder.Entity("Farsight.Rpc.Api.Persistence.Entities.TracingEndpointEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChainId")
                        .HasColumnType("uuid");

                    b.Property<int>("Environment")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ProbedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid");

                    b.Property<string>("TracingMode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChainId");

                    b.HasIndex("ProviderId");

                    b.HasIndex("ApplicationId", "Environment", "ChainId");

                    b.ToTable("rpc_tracing_endpoints", null, t =>
                        {
                            t.HasCheckConstraint("CK_rpc_tracing_endpoints_Address_Scheme", "\"Address\" ~* '^(http|https|ws|wss)://'");
                        });
                });

            modelBuilder.Entity("Farsight.Rpc.Api.Persistence.Entities.ApiClientEntity", b =>
                {
                    b.HasOne("Farsight.Rpc.Api.Persistence.Entities.ApplicationEntity", "Application")
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Application");
                });

            modelBuilder.Entity("Farsight.Rpc.Api.Persistence.Entities.ArchiveEndpointEntity", b =>
                {
                    b.HasOne("Farsight.Rpc.Api.Persistence.Entities.ApplicationEntity", "Application")
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Farsight.Rpc.Api.Persistence.Entities.ChainEntity", "Chain")
                        .WithMany()
                        .HasForeignKey("ChainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Farsight.Rpc.Api.Persistence.Entities.ProviderEntity", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Chain");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Farsight.Rpc.Api.Persistence.Entities.ProviderRateLimitEntity", b =>
                {
                    b.HasOne("Farsight.Rpc.Api.Persistence.Entities.ProviderEntity", "Provider")
                        .WithOne()
                        .HasForeignKey("Farsight.Rpc.Api.Persistence.Entities.ProviderRateLimitEntity", "ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Farsight.Rpc.Api.Persistence.Entities.RealTimeEndpointEntity", b =>
                {
                    b.HasOne("Farsight.Rpc.Api.Persistence.Entities.ApplicationEntity", "Application")
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Farsight.Rpc.Api.Persistence.Entities.ChainEntity", "Chain")
                        .WithMany()
                        .HasForeignKey("ChainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Farsight.Rpc.Api.Persistence.Entities.ProviderEntity", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Chain");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Farsight.Rpc.Api.Persistence.Entities.TracingEndpointEntity", b =>
                {
                    b.HasOne("Farsight.Rpc.Api.Persistence.Entities.ApplicationEntity", "Application")
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Farsight.Rpc.Api.Persistence.Entities.ChainEntity", "Chain")
                        .WithMany()
                        .HasForeignKey("ChainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Farsight.Rpc.Api.Persistence.Entities.ProviderEntity", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Chain");

                    b.Navigation("Provider");
                });
#pragma warning restore 612, 618
        }
    }
}
