// <auto-generated />
using System;
using Farsight.Rpc.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Farsight.Rpc.Api.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260424183743_RenameRpcStructures")]
    partial class RenameRpcStructures
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:CollationDefinition:name_case_insensitive", "und-u-ks-level2,und-u-ks-level2,icu,False")
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Farsight.Rpc.Api.Persistence.Entities.ApplicationEnvironment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string[]>("Chains")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .UseCollation("name_case_insensitive");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId", "Name")
                        .IsUnique();

                    b.ToTable("ApplicationEnvironments", (string)null);
                });

            modelBuilder.Entity("Farsight.Rpc.Api.Persistence.Entities.ConsumerApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("ApplicationId", "EnvironmentId");

                    b.ToTable("ConsumerApiKeys", (string)null);
                });

            modelBuilder.Entity("Farsight.Rpc.Api.Persistence.Entities.ConsumerApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .UseCollation("name_case_insensitive");

                    b.Property<string[]>("Structures")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ConsumerApplications", (string)null);
                });

            modelBuilder.Entity("Farsight.Rpc.Api.Persistence.Entities.Rpc.RpcEndpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Chain")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid");

                    b.Property<string>("RpcType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("ProviderId");

                    b.HasIndex("ApplicationId", "EnvironmentId");

                    b.ToTable("Rpcs", (string)null);

                    b.HasDiscriminator<string>("RpcType").HasValue("RpcEndpoint");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Farsight.Rpc.Api.Persistence.Entities.RpcProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .UseCollation("name_case_insensitive");

                    b.Property<int>("RateLimit")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("RpcProviders", (string)null);
                });

            modelBuilder.Entity("Farsight.Rpc.Api.Persistence.Entities.Rpc.RpcEndpoint+Archive", b =>
                {
                    b.HasBaseType("Farsight.Rpc.Api.Persistence.Entities.Rpc.RpcEndpoint");

                    b.Property<decimal>("IndexerBlockOffset")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("IndexerStepSize")
                        .HasColumnType("numeric(20,0)");

                    b.HasDiscriminator().HasValue("Archive");
                });

            modelBuilder.Entity("Farsight.Rpc.Api.Persistence.Entities.Rpc.RpcEndpoint+Realtime", b =>
                {
                    b.HasBaseType("Farsight.Rpc.Api.Persistence.Entities.Rpc.RpcEndpoint");

                    b.HasDiscriminator().HasValue("Realtime");
                });

            modelBuilder.Entity("Farsight.Rpc.Api.Persistence.Entities.Rpc.RpcEndpoint+Tracing", b =>
                {
                    b.HasBaseType("Farsight.Rpc.Api.Persistence.Entities.Rpc.RpcEndpoint");

                    b.Property<int>("TracingMode")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Tracing");
                });

            modelBuilder.Entity("Farsight.Rpc.Api.Persistence.Entities.ApplicationEnvironment", b =>
                {
                    b.HasOne("Farsight.Rpc.Api.Persistence.Entities.ConsumerApplication", "Application")
                        .WithMany("Environments")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("Farsight.Rpc.Api.Persistence.Entities.ConsumerApiKey", b =>
                {
                    b.HasOne("Farsight.Rpc.Api.Persistence.Entities.ConsumerApplication", "Application")
                        .WithMany("ApiKeys")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Farsight.Rpc.Api.Persistence.Entities.ApplicationEnvironment", "Environment")
                        .WithMany("ApiKeys")
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Environment");
                });

            modelBuilder.Entity("Farsight.Rpc.Api.Persistence.Entities.Rpc.RpcEndpoint", b =>
                {
                    b.HasOne("Farsight.Rpc.Api.Persistence.Entities.ConsumerApplication", "Application")
                        .WithMany("Rpcs")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Farsight.Rpc.Api.Persistence.Entities.ApplicationEnvironment", "Environment")
                        .WithMany("Rpcs")
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Farsight.Rpc.Api.Persistence.Entities.RpcProvider", "Provider")
                        .WithMany("Rpcs")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Environment");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Farsight.Rpc.Api.Persistence.Entities.ApplicationEnvironment", b =>
                {
                    b.Navigation("ApiKeys");

                    b.Navigation("Rpcs");
                });

            modelBuilder.Entity("Farsight.Rpc.Api.Persistence.Entities.ConsumerApplication", b =>
                {
                    b.Navigation("ApiKeys");

                    b.Navigation("Environments");

                    b.Navigation("Rpcs");
                });

            modelBuilder.Entity("Farsight.Rpc.Api.Persistence.Entities.RpcProvider", b =>
                {
                    b.Navigation("Rpcs");
                });
#pragma warning restore 612, 618
        }
    }
}
