// <auto-generated />
using System;
using Farsight.Rpc.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Farsight.Rpc.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260409150140_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Farsight.Rpc.Api.Persistence.Entities.ConsumerApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ConsumerApplications", (string)null);
                });

            modelBuilder.Entity("Farsight.Rpc.Api.Persistence.Entities.Rpc.ArchiveRpc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Chain")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("DexIndexerStepSize")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("Environment")
                        .HasColumnType("integer");

                    b.Property<decimal>("IndexerBlockOffset")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("IndexerStepSize")
                        .HasColumnType("numeric(20,0)");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId");

                    b.HasIndex("ApplicationId", "Environment");

                    b.ToTable("ArchiveRpcs", (string)null);
                });

            modelBuilder.Entity("Farsight.Rpc.Api.Persistence.Entities.Rpc.RealtimeRpc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Chain")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("Environment")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId");

                    b.HasIndex("ApplicationId", "Environment");

                    b.ToTable("RealtimeRpcs", (string)null);
                });

            modelBuilder.Entity("Farsight.Rpc.Api.Persistence.Entities.Rpc.TracingRpc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Chain")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("Environment")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid");

                    b.Property<int>("TracingMode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId");

                    b.HasIndex("ApplicationId", "Environment");

                    b.ToTable("TracingRpcs", (string)null);
                });

            modelBuilder.Entity("Farsight.Rpc.Api.Persistence.Entities.RpcProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RateLimit")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("RpcProviders", (string)null);
                });

            modelBuilder.Entity("Farsight.Rpc.Api.Persistence.Entities.Rpc.ArchiveRpc", b =>
                {
                    b.HasOne("Farsight.Rpc.Api.Persistence.Entities.ConsumerApplication", "Application")
                        .WithMany("ArchiveRpcs")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Farsight.Rpc.Api.Persistence.Entities.RpcProvider", "Provider")
                        .WithMany("ArchiveRpcs")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Farsight.Rpc.Api.Persistence.Entities.Rpc.RealtimeRpc", b =>
                {
                    b.HasOne("Farsight.Rpc.Api.Persistence.Entities.ConsumerApplication", "Application")
                        .WithMany("RealtimeRpcs")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Farsight.Rpc.Api.Persistence.Entities.RpcProvider", "Provider")
                        .WithMany("RealtimeRpcs")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Farsight.Rpc.Api.Persistence.Entities.Rpc.TracingRpc", b =>
                {
                    b.HasOne("Farsight.Rpc.Api.Persistence.Entities.ConsumerApplication", "Application")
                        .WithMany("TracingRpcs")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Farsight.Rpc.Api.Persistence.Entities.RpcProvider", "Provider")
                        .WithMany("TracingRpcs")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Farsight.Rpc.Api.Persistence.Entities.ConsumerApplication", b =>
                {
                    b.Navigation("ArchiveRpcs");

                    b.Navigation("RealtimeRpcs");

                    b.Navigation("TracingRpcs");
                });

            modelBuilder.Entity("Farsight.Rpc.Api.Persistence.Entities.RpcProvider", b =>
                {
                    b.Navigation("ArchiveRpcs");

                    b.Navigation("RealtimeRpcs");

                    b.Navigation("TracingRpcs");
                });
#pragma warning restore 612, 618
        }
    }
}
