// <auto-generated />
using System;
using Farsight.Rpc.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Farsight.Rpc.Api.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260802205144_AddWallets")]
    partial class AddWallets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:CollationDefinition:name_case_insensitive", "und-u-ks-level2,und-u-ks-level2,icu,False")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Farsight.Rpc.Api.Persistence.Entities.ApplicationEnvironment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string[]>("Chains")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<bool>("EnablePublicRpcs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .UseCollation("name_case_insensitive");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId", "Name")
                        .IsUnique();

                    b.ToTable("ApplicationEnvironments", (string)null);
                });

            modelBuilder.Entity("Farsight.Rpc.Api.Persistence.Entities.ConsumerApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("ApplicationId", "EnvironmentId");

                    b.ToTable("ConsumerApiKeys", (string)null);
                });

            modelBuilder.Entity("Farsight.Rpc.Api.Persistence.Entities.ConsumerApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasDefaultValue("#6B7280");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .UseCollation("name_case_insensitive");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ConsumerApplications", (string)null);
                });

            modelBuilder.Entity("Farsight.Rpc.Api.Persistence.Entities.Rpc.RpcEndpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<int[]>("Capabilities")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer[]")
                        .HasDefaultValue(new int[0]);

                    b.Property<string>("Chain")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("EthGetLogsLimit")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("ProviderId");

                    b.HasIndex("ApplicationId", "EnvironmentId");

                    b.HasIndex("ApplicationId", "EnvironmentId", "Chain", "Address")
                        .IsUnique();

                    b.HasIndex("ApplicationId", "EnvironmentId", "Chain", "Order")
                        .IsUnique();

                    b.ToTable("Rpcs", (string)null);
                });

            modelBuilder.Entity("Farsight.Rpc.Api.Persistence.Entities.Rpc.RpcRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<int[]>("AllOf")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.PrimitiveCollection<int[]>("AnyOf")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("ApplicationId", "EnvironmentId");

                    b.ToTable("RpcRules", (string)null);
                });

            modelBuilder.Entity("Farsight.Rpc.Api.Persistence.Entities.RpcErrorGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("Errors")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .UseCollation("name_case_insensitive");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("RpcErrorGroups", (string)null);
                });

            modelBuilder.Entity("Farsight.Rpc.Api.Persistence.Entities.RpcProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .UseCollation("name_case_insensitive");

                    b.Property<int>("RateLimit")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("RpcProviders", (string)null);
                });

            modelBuilder.Entity("Farsight.Rpc.Api.Persistence.Entities.SecurityKeyChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChallengeType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.ToTable("SecurityKeyChallenges", (string)null);

                    b.HasDiscriminator<string>("ChallengeType").HasValue("SecurityKeyChallenge");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Farsight.Rpc.Api.Persistence.Entities.UserSecurityKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AaGuid")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("CredentialId")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<long>("SignatureCounter")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("UserHandle")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CredentialId")
                        .IsUnique();

                    b.HasIndex("Username");

                    b.ToTable("UserSecurityKeys", (string)null);
                });

            modelBuilder.Entity("Farsight.Rpc.Api.Persistence.Entities.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasDefaultValue("#6B7280");

                    b.Property<string>("Mnemonic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .UseCollation("name_case_insensitive");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Wallets", (string)null);
                });

            modelBuilder.Entity("Farsight.Rpc.Api.Persistence.Entities.WalletApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WalletKeyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("WalletKeyId");

                    b.ToTable("WalletApiKeys", (string)null);
                });

            modelBuilder.Entity("Farsight.Rpc.Api.Persistence.Entities.WalletKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Curve")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DerivationPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WalletId", "Curve", "DerivationPath")
                        .IsUnique();

                    b.ToTable("WalletKeys", (string)null);
                });

            modelBuilder.Entity("Farsight.Rpc.Api.Persistence.Entities.SecurityKeyChallenge+Login", b =>
                {
                    b.HasBaseType("Farsight.Rpc.Api.Persistence.Entities.SecurityKeyChallenge");

                    b.Property<string>("Options")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("AssertionOptions");

                    b.HasDiscriminator().HasValue("Login");
                });

            modelBuilder.Entity("Farsight.Rpc.Api.Persistence.Entities.SecurityKeyChallenge+Registration", b =>
                {
                    b.HasBaseType("Farsight.Rpc.Api.Persistence.Entities.SecurityKeyChallenge");

                    b.Property<string>("KeyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Options")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("CredentialCreateOptions");

                    b.HasDiscriminator().HasValue("Registration");
                });

            modelBuilder.Entity("Farsight.Rpc.Api.Persistence.Entities.ApplicationEnvironment", b =>
                {
                    b.HasOne("Farsight.Rpc.Api.Persistence.Entities.ConsumerApplication", "Application")
                        .WithMany("Environments")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("Farsight.Rpc.Api.Persistence.Entities.ConsumerApiKey", b =>
                {
                    b.HasOne("Farsight.Rpc.Api.Persistence.Entities.ConsumerApplication", "Application")
                        .WithMany("ApiKeys")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Farsight.Rpc.Api.Persistence.Entities.ApplicationEnvironment", "Environment")
                        .WithMany("ApiKeys")
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Environment");
                });

            modelBuilder.Entity("Farsight.Rpc.Api.Persistence.Entities.Rpc.RpcEndpoint", b =>
                {
                    b.HasOne("Farsight.Rpc.Api.Persistence.Entities.ConsumerApplication", "Application")
                        .WithMany("Rpcs")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Farsight.Rpc.Api.Persistence.Entities.ApplicationEnvironment", "Environment")
                        .WithMany("Rpcs")
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Farsight.Rpc.Api.Persistence.Entities.RpcProvider", "Provider")
                        .WithMany("Rpcs")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Environment");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Farsight.Rpc.Api.Persistence.Entities.Rpc.RpcRule", b =>
                {
                    b.HasOne("Farsight.Rpc.Api.Persistence.Entities.ConsumerApplication", "Application")
                        .WithMany("RpcRules")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Farsight.Rpc.Api.Persistence.Entities.ApplicationEnvironment", "Environment")
                        .WithMany("RpcRules")
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Environment");
                });

            modelBuilder.Entity("Farsight.Rpc.Api.Persistence.Entities.WalletApiKey", b =>
                {
                    b.HasOne("Farsight.Rpc.Api.Persistence.Entities.WalletKey", "WalletKey")
                        .WithMany("ApiKeys")
                        .HasForeignKey("WalletKeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WalletKey");
                });

            modelBuilder.Entity("Farsight.Rpc.Api.Persistence.Entities.WalletKey", b =>
                {
                    b.HasOne("Farsight.Rpc.Api.Persistence.Entities.Wallet", "Wallet")
                        .WithMany("Keys")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("Farsight.Rpc.Api.Persistence.Entities.ApplicationEnvironment", b =>
                {
                    b.Navigation("ApiKeys");

                    b.Navigation("RpcRules");

                    b.Navigation("Rpcs");
                });

            modelBuilder.Entity("Farsight.Rpc.Api.Persistence.Entities.ConsumerApplication", b =>
                {
                    b.Navigation("ApiKeys");

                    b.Navigation("Environments");

                    b.Navigation("RpcRules");

                    b.Navigation("Rpcs");
                });

            modelBuilder.Entity("Farsight.Rpc.Api.Persistence.Entities.RpcProvider", b =>
                {
                    b.Navigation("Rpcs");
                });

            modelBuilder.Entity("Farsight.Rpc.Api.Persistence.Entities.Wallet", b =>
                {
                    b.Navigation("Keys");
                });

            modelBuilder.Entity("Farsight.Rpc.Api.Persistence.Entities.WalletKey", b =>
                {
                    b.Navigation("ApiKeys");
                });
#pragma warning restore 612, 618
        }
    }
}
